name: Ruby on Rails CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Specify your Ruby version

    - name: Install Dependencies
      run: bundle install

    - name: Run Tests
      run: bundle exec rake test
      env:
        OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        # Other environment variables as needed
